# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-create-pre-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Zip the Build
      run: |
        cd /home/runner/work/MHW-Yet-Another-Overlay-Interface/MHW-Yet-Another-Overlay-Interface/YetAnotherOverlayInterface/bin/Release/net8.0 && zip -r YetAnotherOverlayInterface.zip *

    - name: Expose Commit Data
      uses: rlespinasse/git-commit-data-action@v1
        
    - name: Create Build Release
      id: create-build-release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: 0${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT_SHA }}
        name: Build 0${{ github.run_number }} (${{ env.GIT_COMMIT_SHORT_SHA }})
        draft: false
        prerelease: true
        body: '## [Main Repo](https://github.com/GreenComfyTea/MHW-Yet-Another-Overlay-Interface) | [Commit Files](https://github.com/GreenComfyTea/MHW-Yet-Another-Overlay-Interface/tree/${{ env.GIT_COMMIT_SHA }})'
        token: ${{ secrets.NIGHTLY_TOKEN }}
        repo: MHW-Yet-Another-Overlay-Interface-Nightly
        
    - name: Upload Assets to Build Release
      id: upload-assets-to-build-release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
      with:
        upload_url: ${{ steps.create-build-release.outputs.upload_url }}
        asset_path: /home/runner/work/MHW-Yet-Another-Overlay-Interface/MHW-Yet-Another-Overlay-Interface/YetAnotherOverlayInterface/bin/Release/net8.0/YetAnotherOverlayInterface.zip
        asset_name: YetAnotherOverlayInterface_${{ github.run_number }}_${{ env.GIT_COMMIT_SHORT_SHA }}.zip
        asset_content_type: application/zip
        
    - name: Update Latest Release
      id: update-latest-release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: latest
        name: Nightly 0${{ github.run_number }} (${{ env.GIT_COMMIT_SHORT_SHA }})
        draft: false
        allowUpdates: true
        removeArtifacts: true
        body: '## [Main Repo](https://github.com/GreenComfyTea/MHW-Yet-Another-Overlay-Interface) | [Commit Files](https://github.com/GreenComfyTea/MHW-Yet-Another-Overlay-Interface/tree/${{ env.GIT_COMMIT_SHA }}) | Ignore the date shown for the release. This is the latest build.'
        token: ${{ secrets.NIGHTLY_TOKEN }}
        repo: MHW-Yet-Another-Overlay-Interface-Nightly

    - name: Upload Assets to Latest Release
      id: upload-assets-to-latest-release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
      with:
        upload_url: ${{ steps.update-latest-release.outputs.upload_url }}
        asset_path: /home/runner/work/MHW-Yet-Another-Overlay-Interface/MHW-Yet-Another-Overlay-Interface/YetAnotherOverlayInterface/bin/Release/net8.0/YetAnotherOverlayInterface.zip
        asset_name: YetAnotherOverlayInterface_${{ github.run_number }}_${{ env.GIT_COMMIT_SHORT_SHA }}.zip
        asset_content_type: application/zip